# Numpy

In [2]:
import numpy as np

### adding / removing elements

In [3]:
# create array

np.array([0,1,2,3,4,5,6,7,8,9,10], dtype=int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.zeros((3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
np.ones((2,10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [6]:
np.random.rand(3,4)

array([[0.23589138, 0.82024665, 0.63125639, 0.20708568],
       [0.11449063, 0.29126586, 0.49205141, 0.63591251],
       [0.46008214, 0.45791665, 0.5068899 , 0.74538091]])

In [ ]:
np.random.randn(3,5) # standard normarl (mean 0, std 1) distribution

array([[-0.06723036,  1.12644136, -1.38999597,  1.39782055, -1.66765132],
       [ 0.99971474,  0.52540546,  1.47274185,  0.11869511, -0.36632911],
       [-0.99335875,  0.4981202 , -0.0851935 ,  0.90978677,  0.39193158]])

In [8]:
ndarray = np.ones((2,4))
ndarray

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
ndarray.shape

(2, 4)

In [10]:
ndarray.ndim

2

In [ ]:
# return same data with a new shape
ndarray.reshape(4,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
ndarray.reshape(1,-1)

array([[1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
ndarray.dtype

dtype('float64')

In [14]:
ndarray1 = np.arange(2,22).reshape(4,5)
ndarray1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

In [16]:
ndarray2 = np.arange(0,5).reshape(5,1)
ndarray2

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
# ndarray.dot => dot product 내적
ndarray3 = np.dot(ndarray1,ndarray2)
ndarray3

array([[ 50],
       [100],
       [150],
       [200]])

In [18]:
ndarray3.T

array([[ 50, 100, 150, 200]])

In [20]:
ndarray4 = ndarray3.reshape(2,2)
ndarray4

array([[ 50, 100],
       [150, 200]])

In [21]:
ndarray4.T

array([[ 50, 150],
       [100, 200]])

In [22]:
np.add(ndarray4,ndarray4)

array([[100, 200],
       [300, 400]])

In [23]:
np.subtract(ndarray4, ndarray4.T)

array([[  0, -50],
       [ 50,   0]])